### ISSUE TITLE
Add Cocoapods support

### ISSUE THREAD

**Issue by kirillsh** [pointfreeco/swift-case-paths#2]
Please add cocoapods support

**Comment by stephencelis** [comment]
Hi @kirillsh! Thanks for taking the time to submit an issue. In order to better understand the need to support CocoaPods these days, is there anything that prevents you from using SPM to install this package into your project?

**Comment by Dragna** [comment]
@stephencelis I think it maybe has to do with the fact that when a project is compatible with one dependency management system, you don't want to implement another one in order to minimize the friction of working with that project. Even if Xcode is doing a great work at hiding SPM in the development flow :)

In my team, we use Carthage for instance, we would like to use SPM, but the limitations are too much for us at the moment ( not possible to reference ressources :/ ) so we are sticking to it waiting for the update on that.

**Comment by stephencelis** [comment]
@Dragna Could you still use SPM for any packages that don't need to package resources into a framework, etc.?

There are only a couple reasons I can think of to avoid SPM in an Xcode project these days:

1. The user cannot use Xcode 11 (I'm curious as to what might be preventing users from doing so, since it's been out for awhile and is a requirement for App Store submission)
2. The user already uses a different package manager and wants to use it for everything (but why would this prevent a user from using SPM or another package manager if a desired library doesn't support their manager of choice?)

We've supported CocoaPods and Carthage in all of our other libraries for many years, but we are using the release of CasePaths to reevaluate the need to support both of them, since SPM seems like a viable alternative these days. Maintaining support for CocoaPods and Carthage is a significant cost and the most brittle part of our ability to iterate and release new versions. Some things can be fixed with tooling, and the additional investment required in this kind of tooling feels significant.

If cases can be made for supporting CocoaPods and Carthage (that is, SPM is not even an option), and we have community members interested in managing this support, we're definitely open to it, but I don't think we yet understand why support may be needed when SPM seems to be an available alternative.

**Comment by Dragna** [comment]
I could use SPM yes. and as a matter of fact that is how I will use it ^^. (it will help me make the continuous integration team of my company work on SPM integration 😛 ) 

I was just giving a possible explanation on why @kirillsh asked for cocoa pods support.

**Comment by kirillsh** [comment]
thx @Dragna for the explanation.
The goal in our company is to have a unified solution for package management and we have it with pods. One more reason is SPM packages are not cached on our CI versus pod ones.

**Comment by sergdort** [comment]
Hey guys, I guess an argument for Cocoapods support could be that other libraries may want to use CasePaths as dependencies. (Like me 🙈 )

**Comment by bitomule** [comment]
I'm also interested in using CasePaths as a dependency to other Cocoapods lib. The only alternative now is adding CasePaths code into my lib. Using SPM is far from being an option for all of us.

**Comment by stephencelis** [comment]
We're going to close this for now, since SPM has gotten more and more integrated into Xcode and Swift development. We understand folks are still using CocoaPods out there, and requirements like yours, @sergdort, but the amount of time spent supporting all the flavors of package managers across our projects was significant enough that we don't have the bandwidth for it.

If you'd like to fork CasePaths to provide a CocoaPods- or Carthage-friendly repo, we encourage it! You can also freely vendor CasePaths code in your library.
